/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameGameSlugIndexRouteImport } from './routes/game/$gameSlug/index'
import { Route as GameGameSlugIntroRouteImport } from './routes/game/$gameSlug/intro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameSlugIndexRoute = GameGameSlugIndexRouteImport.update({
  id: '/game/$gameSlug/',
  path: '/game/$gameSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameSlugIntroRoute = GameGameSlugIntroRouteImport.update({
  id: '/game/$gameSlug/intro',
  path: '/game/$gameSlug/intro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$gameSlug/intro': typeof GameGameSlugIntroRoute
  '/game/$gameSlug': typeof GameGameSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$gameSlug/intro': typeof GameGameSlugIntroRoute
  '/game/$gameSlug': typeof GameGameSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$gameSlug/intro': typeof GameGameSlugIntroRoute
  '/game/$gameSlug/': typeof GameGameSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/$gameSlug/intro' | '/game/$gameSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/$gameSlug/intro' | '/game/$gameSlug'
  id: '__root__' | '/' | '/game/$gameSlug/intro' | '/game/$gameSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameGameSlugIntroRoute: typeof GameGameSlugIntroRoute
  GameGameSlugIndexRoute: typeof GameGameSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameSlug/': {
      id: '/game/$gameSlug/'
      path: '/game/$gameSlug'
      fullPath: '/game/$gameSlug'
      preLoaderRoute: typeof GameGameSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameSlug/intro': {
      id: '/game/$gameSlug/intro'
      path: '/game/$gameSlug/intro'
      fullPath: '/game/$gameSlug/intro'
      preLoaderRoute: typeof GameGameSlugIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameGameSlugIntroRoute: GameGameSlugIntroRoute,
  GameGameSlugIndexRoute: GameGameSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
